name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ruslanys/wrk

    - uses: actions/checkout@v4
    - name: Publish the Docker image
      env:
        HUB_TOKEN: ${{ secrets.HUB_TOKEN }}
      run: |
        docker login -u ruslanys -p $HUB_TOKEN
        docker push ruslanys/wrk
